runtime: python310
entrypoint: gunicorn -b :$PORT src:app

env_variables:
  SECRET_KEY : dev
  FLASK_ENV : development
  FLASK_APP : src
  SQLALCHEMY_DATABASE_URI : postgresql://postgres:postgres@35.247.244.29:5432/monig
  TEST_DATABASE_URI : sqlite:///test.db
  FLASK_DEBUG : 1
  PORT : 8080
