runtime: python310
entrypoint: gunicorn -b :$PORT src.__init__:app

env_variables:
  SECRET_KEY : dev
  FLASK_ENV : development
  FLASK_APP : src
  SQLALCHEMY_DATABASE_URI : postgresql://postgres:postgres@/monig?host=/cloudsql/monig-382213:southamerica-east1:monig&unix_socket=/cloudsql/monig-382213:southamerica-east1:monig

  TEST_DATABASE_URI : sqlite:///test.db
  FLASK_DEBUG : 1
  PORT : 8080