steps:
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args:
  - "-c"
  - |
    gcloud app deploy --no-cache --log-http --logs-dir=gs://monig-382019.appspot.com

options_:
  logging: CLOUD_LOGGING_ONLY
  artifacts:
    objects:
      location: "us.artifacts.monig-382019.appspot.com"
      paths:
      - "*/**"
