steps:
# Compilação do container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/monig-382213/monig', '.']

#push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/monig-382213/monig']


# Implantação no Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'monig'
    - '--image=gcr.io/monig-382213/gcloud'
    - '--platform=managed'
    - '--region=southamerica-east1'
    - '--allow-unauthenticated'
    - '--memory=2Gi'
    - '--set-env-vars=FLASK_ENV=development,SECRET_KEY=prod,SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@34.151.208.233:5432/monig,TEST_DATABASE_URI=sqlite:///test.db,FLASK_DEBUG=1'
timeout: 1800s
