branch-defaults:
  main:
    environment: null
    group_suffix: null
global:
  application_name: flask-tutorial
  branch: main
  default_ec2_keyname: ec2
  default_platform: Python 3.7
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: origin
  sc: git
  workspace_type: Application
