[
   {
      "essential": true,
      "name":"flask-app",
      "image":"${REPOSITORY_URL}",
      "hardTimeout": 300,
      "cpu":516,
      "memory":1024,
      "portMappings":[
         {
            "containerPort":5000,
            "hostPort":5000,
            "protocol":"tcp"
         }
      ],
      "logConfiguration": {
        "logDriver" : "awslogs",
        "options" : {
          "awslogs-create-group": "true",
          "awslogs-region" : "us-east-2",
          "awslogs-group" : "log-cluster-flask",
          "awslogs-stream-prefix": "flask-app"
        }
      },
      "environment":[
         {
            "name":"SECRET_KEY",
            "value":"${SECRET_KEY}"
         },
         {
            "name":"SQLALCHEMY_DATABASE_URI",
            "value":"${SQLALCHEMY_DATABASE_URI}"
         },
         {
            "name":"SQLALCHEMY_DATABASE_URI_ASNC",
            "value":"${SQLALCHEMY_DATABASE_URI_ASNC}"
         },
         {
            "name":"JWT_SECRET_KEY",
            "value":"${JWT_SECRET_KEY}"
         },
         {
            "name":"TZ",
            "value":"${TZ}"
         },
         {
            "name":"DB_TEST",
            "value":"${DB_TEST}"
         },
         {
            "name":"SESSION_TYPE",
            "value":"${SESSION_TYPE}"
         },
         {
            "name":"PORT",
            "value":"${PORT}"
         },
         {
            "name":"FLASK_DEBUG",
            "value":"${FLASK_DEBUG}"
         },
         {
            "name":"POSTGRES_USER",
            "value":"${POSTGRES_USERNAME}"
         },
         {
            "name":"POSTGRES_PASSWORD",
            "value":"${POSTGRES_PASSWD}"
         },
         {
            "name":"POSTGRES_ENDPOINT",
            "value":"${POSTGRES_ENDPOINT}"
         },
         {
            "name":"POSTGRES_DATABASE",
            "value":"${POSTGRES_DATABASE}"
         },
         {
            "name":"FLASK_APP",
            "value":"${FLASK_APP}"
         },
         {
            "name":"FLASK_ENV",
            "value":"${FLASK_ENV}"
         },
         {
            "name":"APP_HOME",
            "value":"${FLASK_APP_HOME}"
         },
         {
            "name":"APP_PORT",
            "value":"${APP_PORT}"
         },
         {
            "name":"APP_SECRET_KEY",
            "value":"${APP_SECRET_KEY}"
         }
      ]
   }
]