"""empty message

Revision ID: 1620e65330a5
Revises: fb690082cf58
Create Date: 2023-10-19 20:39:55.797620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1620e65330a5'
down_revision = 'fb690082cf58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumo_agua_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('consumo', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('data', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('dataFimPeriodo', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('dataInicioPeriodo', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('valor', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('fk_hidrometro', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('fk_escola', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='main'
    )
    with op.batch_alter_table('consumo_agua_version', schema='main') as batch_op:
        batch_op.create_index(batch_op.f('ix_main_consumo_agua_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_consumo_agua_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_consumo_agua_version_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('aux_tipo_de_eventos', schema='main') as batch_op:
        batch_op.drop_column('acao')

    with op.batch_alter_table('eventos', schema='main') as batch_op:
        batch_op.add_column(sa.Column('encerramento', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_encerramento', sa.DateTime(), nullable=True))

    with op.batch_alter_table('eventos_version', schema='main') as batch_op:
        batch_op.add_column(sa.Column('encerramento', sa.Boolean(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_encerramento', sa.DateTime(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos_version', schema='main') as batch_op:
        batch_op.drop_column('data_encerramento')
        batch_op.drop_column('encerramento')

    with op.batch_alter_table('eventos', schema='main') as batch_op:
        batch_op.drop_column('data_encerramento')
        batch_op.drop_column('encerramento')

    with op.batch_alter_table('aux_tipo_de_eventos', schema='main') as batch_op:
        batch_op.add_column(sa.Column('acao', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('consumo_agua_version', schema='main') as batch_op:
        batch_op.drop_index(batch_op.f('ix_main_consumo_agua_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_main_consumo_agua_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_main_consumo_agua_version_end_transaction_id'))

    op.drop_table('consumo_agua_version', schema='main')
    # ### end Alembic commands ###
