"""validação

Revision ID: 4d75cd472c78
Revises: a2991932902a
Create Date: 2023-09-25 12:03:26.413154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d75cd472c78'
down_revision = 'a2991932902a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema='main') as batch_op:
        batch_op.drop_column('valor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema='main') as batch_op:
        batch_op.add_column(sa.Column('valor', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
