"""empty message

Revision ID: 5dde578b7d2b
Revises: 
Create Date: 2023-10-19 17:58:13.277018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dde578b7d2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_umida_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('fk_edificios', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('tipo_area_umida', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('status_area_umida', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('operacao_area_umida', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('nome_area_umida', sa.String(), autoincrement=False, nullable=True),
    sa.Column('localizacao_area_umida', sa.String(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='main'
    )
    with op.batch_alter_table('area_umida_version', schema='main') as batch_op:
        batch_op.create_index(batch_op.f('ix_main_area_umida_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_area_umida_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_area_umida_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('aux_customizado_cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nivel_escola', sa.String(), nullable=True),
    sa.Column('tipo_area_umida', sa.String(), nullable=True),
    sa.Column('status_area_umida', sa.String(), nullable=True),
    sa.Column('tipo_equipamento', sa.String(), nullable=True),
    sa.Column('descricao_equipamento', sa.String(), nullable=True),
    sa.Column('periodo_populacao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('aux_de_locais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_da_tabela', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('aux_operacao_area_umida',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operacao', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operacao'),
    schema='main'
    )
    op.create_table('aux_opniveis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nivel', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nivel'),
    schema='main'
    )
    op.create_table('aux_populacao_periodos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('periodo', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('aux_tipo_area_umida',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo'),
    schema='main'
    )
    op.create_table('aux_tipo_equipamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aparelho_sanitario', sa.String(), nullable=False),
    sa.Column('vazao', sa.Float(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('aux_tipo_hidrometros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_hidrometro', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=55), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('telefone', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome'),
    schema='main'
    )
    op.create_table('edificios_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('fk_escola', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('numero_edificio', sa.String(), autoincrement=False, nullable=True),
    sa.Column('nome_do_edificio', sa.String(), autoincrement=False, nullable=True),
    sa.Column('principal', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('cep_edificio', sa.String(), autoincrement=False, nullable=True),
    sa.Column('bairro_edificio', sa.String(), autoincrement=False, nullable=True),
    sa.Column('cidade_edificio', sa.String(), autoincrement=False, nullable=True),
    sa.Column('estado_edificio', sa.String(), autoincrement=False, nullable=True),
    sa.Column('cnpj_edificio', sa.String(), autoincrement=False, nullable=True),
    sa.Column('logradouro_edificio', sa.String(), autoincrement=False, nullable=True),
    sa.Column('complemento_edificio', sa.String(), autoincrement=False, nullable=True),
    sa.Column('pavimentos_edificio', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('area_total_edificio', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('capacidade_reuso_m3_edificio', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('agua_de_reuso', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='main'
    )
    with op.batch_alter_table('edificios_version', schema='main') as batch_op:
        batch_op.create_index(batch_op.f('ix_main_edificios_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_edificios_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_edificios_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('equipamentos_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('fk_area_umida', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('tipo_equipamento', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('quantTotal', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('quantProblema', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('quantInutil', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='main'
    )
    with op.batch_alter_table('equipamentos_version', schema='main') as batch_op:
        batch_op.create_index(batch_op.f('ix_main_equipamentos_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_equipamentos_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_equipamentos_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('escola_niveis_version',
    sa.Column('escola_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nivel_ensino_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('escola_id', 'nivel_ensino_id', 'transaction_id'),
    schema='main'
    )
    with op.batch_alter_table('escola_niveis_version', schema='main') as batch_op:
        batch_op.create_index(batch_op.f('ix_main_escola_niveis_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_escola_niveis_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_escola_niveis_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('escolas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(length=25), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    schema='main'
    )
    op.create_table('escolas_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.String(), autoincrement=False, nullable=True),
    sa.Column('cnpj', sa.String(), autoincrement=False, nullable=True),
    sa.Column('email', sa.String(), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.String(length=25), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='main'
    )
    with op.batch_alter_table('escolas_version', schema='main') as batch_op:
        batch_op.create_index(batch_op.f('ix_main_escolas_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_escolas_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_escolas_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('eventos_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('fk_tipo', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.String(), autoincrement=False, nullable=True),
    sa.Column('datainicio', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('datafim', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('local', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('tipo_de_local', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('observacao', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='main'
    )
    with op.batch_alter_table('eventos_version', schema='main') as batch_op:
        batch_op.create_index(batch_op.f('ix_main_eventos_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_eventos_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_eventos_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('hidrometros_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('fk_edificios', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('fk_hidrometro', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('hidrometro', sa.String(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='main'
    )
    with op.batch_alter_table('hidrometros_version', schema='main') as batch_op:
        batch_op.create_index(batch_op.f('ix_main_hidrometros_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_hidrometros_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_hidrometros_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('populacao_niveis_version',
    sa.Column('populacao_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nivel_escola_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('populacao_id', 'nivel_escola_id', 'transaction_id'),
    schema='main'
    )
    with op.batch_alter_table('populacao_niveis_version', schema='main') as batch_op:
        batch_op.create_index(batch_op.f('ix_main_populacao_niveis_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_populacao_niveis_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_populacao_niveis_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('populacao_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('fk_edificios', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('fk_niveis', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('fk_periodo', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('funcionarios', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('alunos', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='main'
    )
    with op.batch_alter_table('populacao_version', schema='main') as batch_op:
        batch_op.create_index(batch_op.f('ix_main_populacao_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_populacao_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_populacao_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('reservatorio_edificio_version',
    sa.Column('edificio_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('reservatorio_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('edificio_id', 'reservatorio_id', 'transaction_id'),
    schema='main'
    )
    with op.batch_alter_table('reservatorio_edificio_version', schema='main') as batch_op:
        batch_op.create_index(batch_op.f('ix_main_reservatorio_edificio_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_reservatorio_edificio_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_reservatorio_edificio_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('reservatorios_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('fk_escola', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('nome_do_reservatorio', sa.String(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='main'
    )
    with op.batch_alter_table('reservatorios_version', schema='main') as batch_op:
        batch_op.create_index(batch_op.f('ix_main_reservatorios_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_reservatorios_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_reservatorios_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('usuarios_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('email', sa.String(), autoincrement=False, nullable=True),
    sa.Column('senha', sa.String(length=126), autoincrement=False, nullable=True),
    sa.Column('cod_cliente', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id'),
    schema='main'
    )
    with op.batch_alter_table('usuarios_version', schema='main') as batch_op:
        batch_op.create_index(batch_op.f('ix_main_usuarios_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_usuarios_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_main_usuarios_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('aux_area_umida_equipamento',
    sa.Column('tipo_equipamento_id', sa.Integer(), nullable=False),
    sa.Column('tipo_area_umida_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_area_umida_id'], ['main.aux_tipo_area_umida.id'], ),
    sa.ForeignKeyConstraint(['tipo_equipamento_id'], ['main.aux_tipo_equipamentos.id'], ),
    sa.PrimaryKeyConstraint('tipo_equipamento_id', 'tipo_area_umida_id'),
    schema='main'
    )
    op.create_table('edificios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_escola', sa.Integer(), nullable=True),
    sa.Column('numero_edificio', sa.String(), nullable=True),
    sa.Column('nome_do_edificio', sa.String(), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=True),
    sa.Column('cep_edificio', sa.String(), nullable=True),
    sa.Column('bairro_edificio', sa.String(), nullable=True),
    sa.Column('cidade_edificio', sa.String(), nullable=True),
    sa.Column('estado_edificio', sa.String(), nullable=True),
    sa.Column('cnpj_edificio', sa.String(), nullable=True),
    sa.Column('logradouro_edificio', sa.String(), nullable=True),
    sa.Column('complemento_edificio', sa.String(), nullable=True),
    sa.Column('pavimentos_edificio', sa.Integer(), nullable=True),
    sa.Column('area_total_edificio', sa.Float(), nullable=True),
    sa.Column('capacidade_reuso_m3_edificio', sa.Float(), nullable=True),
    sa.Column('agua_de_reuso', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_escola'], ['main.escolas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('escola_niveis',
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('nivel_ensino_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['main.escolas.id'], ),
    sa.ForeignKeyConstraint(['nivel_ensino_id'], ['main.aux_opniveis.id'], ),
    sa.PrimaryKeyConstraint('escola_id', 'nivel_ensino_id'),
    schema='main'
    )
    op.create_table('reservatorios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_escola', sa.Integer(), nullable=True),
    sa.Column('nome_do_reservatorio', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_escola'], ['main.escolas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(length=126), nullable=False),
    sa.Column('cod_cliente', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cod_cliente'], ['main.cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='main'
    )
    op.create_table('area_umida',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_edificios', sa.Integer(), nullable=True),
    sa.Column('tipo_area_umida', sa.Integer(), nullable=True),
    sa.Column('status_area_umida', sa.Boolean(), nullable=True),
    sa.Column('operacao_area_umida', sa.Integer(), nullable=True),
    sa.Column('nome_area_umida', sa.String(), nullable=True),
    sa.Column('localizacao_area_umida', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_edificios'], ['main.edificios.id'], ),
    sa.ForeignKeyConstraint(['operacao_area_umida'], ['main.aux_operacao_area_umida.id'], ),
    sa.ForeignKeyConstraint(['tipo_area_umida'], ['main.aux_tipo_area_umida.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('aux_tipo_de_eventos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_cliente', sa.Integer(), nullable=True),
    sa.Column('nome_do_tipo_de_evento', sa.String(), nullable=True),
    sa.Column('recorrente', sa.Boolean(), nullable=True),
    sa.Column('dia', sa.Integer(), nullable=True),
    sa.Column('mes', sa.Integer(), nullable=True),
    sa.Column('requer_acao', sa.Boolean(), nullable=True),
    sa.Column('tempo', sa.Integer(), nullable=True),
    sa.Column('unidade', sa.String(), nullable=True),
    sa.Column('acao', sa.Boolean(), nullable=True),
    sa.Column('usuario', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_cliente'], ['main.cliente.id'], ),
    sa.ForeignKeyConstraint(['usuario'], ['main.usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('hidrometros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_edificios', sa.Integer(), nullable=True),
    sa.Column('fk_hidrometro', sa.Integer(), nullable=True),
    sa.Column('hidrometro', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_edificios'], ['main.edificios.id'], ),
    sa.ForeignKeyConstraint(['fk_hidrometro'], ['main.aux_tipo_hidrometros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('populacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_edificios', sa.Integer(), nullable=True),
    sa.Column('fk_niveis', sa.Integer(), nullable=True),
    sa.Column('fk_periodo', sa.Integer(), nullable=True),
    sa.Column('funcionarios', sa.Integer(), nullable=True),
    sa.Column('alunos', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_edificios'], ['main.edificios.id'], ),
    sa.ForeignKeyConstraint(['fk_niveis'], ['main.aux_opniveis.id'], ),
    sa.ForeignKeyConstraint(['fk_periodo'], ['main.aux_populacao_periodos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('reservatorio_edificio',
    sa.Column('edificio_id', sa.Integer(), nullable=False),
    sa.Column('reservatorio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['edificio_id'], ['main.edificios.id'], ),
    sa.ForeignKeyConstraint(['reservatorio_id'], ['main.reservatorios.id'], ),
    sa.PrimaryKeyConstraint('edificio_id', 'reservatorio_id'),
    schema='main'
    )
    op.create_table('consumo_agua',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('consumo_m3', sa.Integer(), nullable=False),
    sa.Column('inicio_medicao', sa.DateTime(), nullable=True),
    sa.Column('fim_medicao', sa.DateTime(), nullable=True),
    sa.Column('fk_hidrometro', sa.Integer(), nullable=True),
    sa.Column('fk_escola', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_escola'], ['main.escolas.id'], ),
    sa.ForeignKeyConstraint(['fk_hidrometro'], ['main.hidrometros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consumo_m3'),
    schema='main'
    )
    op.create_table('equipamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_area_umida', sa.Integer(), nullable=True),
    sa.Column('tipo_equipamento', sa.Integer(), nullable=True),
    sa.Column('quantTotal', sa.Integer(), nullable=True),
    sa.Column('quantProblema', sa.Integer(), nullable=True),
    sa.Column('quantInutil', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_area_umida'], ['main.area_umida.id'], ),
    sa.ForeignKeyConstraint(['tipo_equipamento'], ['main.aux_tipo_equipamentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_tipo', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('datainicio', sa.DateTime(), nullable=True),
    sa.Column('datafim', sa.DateTime(), nullable=True),
    sa.Column('local', sa.Integer(), nullable=True),
    sa.Column('tipo_de_local', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_tipo'], ['main.aux_tipo_de_eventos.id'], ),
    sa.ForeignKeyConstraint(['tipo_de_local'], ['main.aux_de_locais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('populacao_niveis',
    sa.Column('populacao_id', sa.Integer(), nullable=False),
    sa.Column('nivel_escola_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nivel_escola_id'], ['main.aux_opniveis.id'], ),
    sa.ForeignKeyConstraint(['populacao_id'], ['main.populacao.id'], ),
    sa.PrimaryKeyConstraint('populacao_id', 'nivel_escola_id'),
    schema='main'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('populacao_niveis', schema='main')
    op.drop_table('eventos', schema='main')
    op.drop_table('equipamentos', schema='main')
    op.drop_table('consumo_agua', schema='main')
    op.drop_table('reservatorio_edificio', schema='main')
    op.drop_table('populacao', schema='main')
    op.drop_table('hidrometros', schema='main')
    op.drop_table('aux_tipo_de_eventos', schema='main')
    op.drop_table('area_umida', schema='main')
    op.drop_table('usuarios', schema='main')
    op.drop_table('reservatorios', schema='main')
    op.drop_table('escola_niveis', schema='main')
    op.drop_table('edificios', schema='main')
    op.drop_table('aux_area_umida_equipamento', schema='main')
    with op.batch_alter_table('usuarios_version', schema='main') as batch_op:
        batch_op.drop_index(batch_op.f('ix_main_usuarios_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_main_usuarios_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_main_usuarios_version_end_transaction_id'))

    op.drop_table('usuarios_version', schema='main')
    with op.batch_alter_table('reservatorios_version', schema='main') as batch_op:
        batch_op.drop_index(batch_op.f('ix_main_reservatorios_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_main_reservatorios_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_main_reservatorios_version_end_transaction_id'))

    op.drop_table('reservatorios_version', schema='main')
    with op.batch_alter_table('reservatorio_edificio_version', schema='main') as batch_op:
        batch_op.drop_index(batch_op.f('ix_main_reservatorio_edificio_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_main_reservatorio_edificio_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_main_reservatorio_edificio_version_end_transaction_id'))

    op.drop_table('reservatorio_edificio_version', schema='main')
    with op.batch_alter_table('populacao_version', schema='main') as batch_op:
        batch_op.drop_index(batch_op.f('ix_main_populacao_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_main_populacao_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_main_populacao_version_end_transaction_id'))

    op.drop_table('populacao_version', schema='main')
    with op.batch_alter_table('populacao_niveis_version', schema='main') as batch_op:
        batch_op.drop_index(batch_op.f('ix_main_populacao_niveis_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_main_populacao_niveis_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_main_populacao_niveis_version_end_transaction_id'))

    op.drop_table('populacao_niveis_version', schema='main')
    with op.batch_alter_table('hidrometros_version', schema='main') as batch_op:
        batch_op.drop_index(batch_op.f('ix_main_hidrometros_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_main_hidrometros_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_main_hidrometros_version_end_transaction_id'))

    op.drop_table('hidrometros_version', schema='main')
    with op.batch_alter_table('eventos_version', schema='main') as batch_op:
        batch_op.drop_index(batch_op.f('ix_main_eventos_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_main_eventos_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_main_eventos_version_end_transaction_id'))

    op.drop_table('eventos_version', schema='main')
    with op.batch_alter_table('escolas_version', schema='main') as batch_op:
        batch_op.drop_index(batch_op.f('ix_main_escolas_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_main_escolas_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_main_escolas_version_end_transaction_id'))

    op.drop_table('escolas_version', schema='main')
    op.drop_table('escolas', schema='main')
    with op.batch_alter_table('escola_niveis_version', schema='main') as batch_op:
        batch_op.drop_index(batch_op.f('ix_main_escola_niveis_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_main_escola_niveis_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_main_escola_niveis_version_end_transaction_id'))

    op.drop_table('escola_niveis_version', schema='main')
    with op.batch_alter_table('equipamentos_version', schema='main') as batch_op:
        batch_op.drop_index(batch_op.f('ix_main_equipamentos_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_main_equipamentos_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_main_equipamentos_version_end_transaction_id'))

    op.drop_table('equipamentos_version', schema='main')
    with op.batch_alter_table('edificios_version', schema='main') as batch_op:
        batch_op.drop_index(batch_op.f('ix_main_edificios_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_main_edificios_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_main_edificios_version_end_transaction_id'))

    op.drop_table('edificios_version', schema='main')
    op.drop_table('cliente', schema='main')
    op.drop_table('aux_tipo_hidrometros', schema='main')
    op.drop_table('aux_tipo_equipamentos', schema='main')
    op.drop_table('aux_tipo_area_umida', schema='main')
    op.drop_table('aux_populacao_periodos', schema='main')
    op.drop_table('aux_opniveis', schema='main')
    op.drop_table('aux_operacao_area_umida', schema='main')
    op.drop_table('aux_de_locais', schema='main')
    op.drop_table('aux_customizado_cliente', schema='main')
    with op.batch_alter_table('area_umida_version', schema='main') as batch_op:
        batch_op.drop_index(batch_op.f('ix_main_area_umida_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_main_area_umida_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_main_area_umida_version_end_transaction_id'))

    op.drop_table('area_umida_version', schema='main')
    # ### end Alembic commands ###
