"""inserindo valor cliente

Revision ID: a2991932902a
Revises: 1d670465394e
Create Date: 2023-09-25 11:23:00.256743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2991932902a'
down_revision = '1d670465394e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema='main') as batch_op:
        batch_op.add_column(sa.Column('valor', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema='main') as batch_op:
        batch_op.drop_column('valor')

    # ### end Alembic commands ###
