"""empty message

Revision ID: b462d3c7f6eb
Revises: c6c58eb53136
Create Date: 2023-10-24 21:11:00.279780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b462d3c7f6eb'
down_revision = 'c6c58eb53136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    with op.batch_alter_table('eventos', schema='main') as batch_op:
        batch_op.add_column(sa.Column('fk_escola', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'escolas', ['fk_escola'], ['id'], referent_schema='main')

    with op.batch_alter_table('eventos_version', schema='main') as batch_op:
        batch_op.add_column(sa.Column('fk_escola', sa.Integer(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos_version', schema='main') as batch_op:
        batch_op.drop_column('fk_escola')

    with op.batch_alter_table('eventos', schema='main') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fk_escola')

    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # ### end Alembic commands ###
