"""empty message

Revision ID: c6c58eb53136
Revises: 
Create Date: 2023-10-24 17:37:34.298528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c58eb53136'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('consumo_agua_version',
    # sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    # sa.Column('consumo', sa.Integer(), autoincrement=False, nullable=True),
    # sa.Column('data', sa.DateTime(), autoincrement=False, nullable=True),
    # sa.Column('dataFimPeriodo', sa.DateTime(), autoincrement=False, nullable=True),
    # sa.Column('dataInicioPeriodo', sa.DateTime(), autoincrement=False, nullable=True),
    # sa.Column('valor', sa.Float(), autoincrement=False, nullable=True),
    # sa.Column('fk_hidrometro', sa.Integer(), autoincrement=False, nullable=True),
    # sa.Column('fk_escola', sa.Integer(), autoincrement=False, nullable=True),
    # sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=True),
    # sa.Column('updated_at', sa.DateTime(), autoincrement=False, nullable=True),
    # sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    # sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    # sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    # sa.PrimaryKeyConstraint('id', 'transaction_id'),
    # schema='main'
    # )
    # with op.batch_alter_table('consumo_agua_version', schema='main') as batch_op:
    #     batch_op.create_index(batch_op.f('ix_main_consumo_agua_version_end_transaction_id'), ['end_transaction_id'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_main_consumo_agua_version_operation_type'), ['operation_type'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_main_consumo_agua_version_transaction_id'), ['transaction_id'], unique=False)

    # op.create_table('consumo_agua',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('consumo', sa.Integer(), nullable=False),
    # sa.Column('data', sa.DateTime(), nullable=True),
    # sa.Column('dataFimPeriodo', sa.DateTime(), nullable=True),
    # sa.Column('dataInicioPeriodo', sa.DateTime(), nullable=True),
    # sa.Column('valor', sa.Float(), nullable=True),
    # sa.Column('fk_hidrometro', sa.Integer(), nullable=True),
    # sa.Column('fk_escola', sa.Integer(), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('updated_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['fk_escola'], ['main.escolas.id'], ),
    # sa.ForeignKeyConstraint(['fk_hidrometro'], ['main.hidrometros.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('consumo'),
    # schema='main'
    # )
    # op.drop_table('spatial_ref_sys')
    # with op.batch_alter_table('area_umida', schema='main') as batch_op:
    #     batch_op.drop_column('status_do_registro')

    # with op.batch_alter_table('area_umida_version', schema='main') as batch_op:
    #     batch_op.drop_column('status_do_registro')

    # with op.batch_alter_table('aux_tipo_de_eventos', schema='main') as batch_op:
    #     batch_op.drop_column('acao')
    #     batch_op.drop_column('status_do_registro')

    # with op.batch_alter_table('edificios', schema='main') as batch_op:
    #     batch_op.drop_column('status_do_registro')

    # with op.batch_alter_table('edificios_version', schema='main') as batch_op:
    #     batch_op.drop_column('status_do_registro')

    # with op.batch_alter_table('equipamentos', schema='main') as batch_op:
    #     batch_op.drop_column('status_do_registro')

    # with op.batch_alter_table('equipamentos_version', schema='main') as batch_op:
    #     batch_op.drop_column('status_do_registro')

    # with op.batch_alter_table('escolas', schema='main') as batch_op:
    #     batch_op.drop_column('status_do_registro')

    # with op.batch_alter_table('escolas_version', schema='main') as batch_op:
    #     batch_op.drop_column('status_do_registro')

    # with op.batch_alter_table('eventos', schema='main') as batch_op:
    #     batch_op.add_column(sa.Column('encerramento', sa.Boolean(), nullable=True))
    #     batch_op.add_column(sa.Column('data_encerramento', sa.DateTime(), nullable=True))

    # with op.batch_alter_table('eventos_version', schema='main') as batch_op:
    #     batch_op.add_column(sa.Column('encerramento', sa.Boolean(), autoincrement=False, nullable=True))
    #     batch_op.add_column(sa.Column('data_encerramento', sa.DateTime(), autoincrement=False, nullable=True))

    # with op.batch_alter_table('hidrometros', schema='main') as batch_op:
    #     batch_op.drop_column('status_do_registro')

    # with op.batch_alter_table('hidrometros_version', schema='main') as batch_op:
    #     batch_op.drop_column('status_do_registro')

    # with op.batch_alter_table('populacao', schema='main') as batch_op:
    #     batch_op.drop_column('status_do_registro')

    # with op.batch_alter_table('populacao_version', schema='main') as batch_op:
    #     batch_op.drop_column('status_do_registro')

    # with op.batch_alter_table('reservatorios', schema='main') as batch_op:
    #     batch_op.drop_column('status_do_registro')

    # with op.batch_alter_table('reservatorios_version', schema='main') as batch_op:
    #     batch_op.drop_column('status_do_registro')

    # ### end Alembic commands ###
    pass

def downgrade():
    # # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('reservatorios_version', schema='main') as batch_op:
    #     batch_op.add_column(sa.Column('status_do_registro', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # with op.batch_alter_table('reservatorios', schema='main') as batch_op:
    #     batch_op.add_column(sa.Column('status_do_registro', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # with op.batch_alter_table('populacao_version', schema='main') as batch_op:
    #     batch_op.add_column(sa.Column('status_do_registro', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # with op.batch_alter_table('populacao', schema='main') as batch_op:
    #     batch_op.add_column(sa.Column('status_do_registro', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # with op.batch_alter_table('hidrometros_version', schema='main') as batch_op:
    #     batch_op.add_column(sa.Column('status_do_registro', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # with op.batch_alter_table('hidrometros', schema='main') as batch_op:
    #     batch_op.add_column(sa.Column('status_do_registro', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # with op.batch_alter_table('eventos_version', schema='main') as batch_op:
    #     batch_op.drop_column('data_encerramento')
    #     batch_op.drop_column('encerramento')

    # with op.batch_alter_table('eventos', schema='main') as batch_op:
    #     batch_op.drop_column('data_encerramento')
    #     batch_op.drop_column('encerramento')

    # with op.batch_alter_table('escolas_version', schema='main') as batch_op:
    #     batch_op.add_column(sa.Column('status_do_registro', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # with op.batch_alter_table('escolas', schema='main') as batch_op:
    #     batch_op.add_column(sa.Column('status_do_registro', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # with op.batch_alter_table('equipamentos_version', schema='main') as batch_op:
    #     batch_op.add_column(sa.Column('status_do_registro', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # with op.batch_alter_table('equipamentos', schema='main') as batch_op:
    #     batch_op.add_column(sa.Column('status_do_registro', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # with op.batch_alter_table('edificios_version', schema='main') as batch_op:
    #     batch_op.add_column(sa.Column('status_do_registro', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # with op.batch_alter_table('edificios', schema='main') as batch_op:
    #     batch_op.add_column(sa.Column('status_do_registro', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # with op.batch_alter_table('aux_tipo_de_eventos', schema='main') as batch_op:
    #     batch_op.add_column(sa.Column('status_do_registro', sa.BOOLEAN(), autoincrement=False, nullable=True))
    #     batch_op.add_column(sa.Column('acao', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # with op.batch_alter_table('area_umida_version', schema='main') as batch_op:
    #     batch_op.add_column(sa.Column('status_do_registro', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # with op.batch_alter_table('area_umida', schema='main') as batch_op:
    #     batch_op.add_column(sa.Column('status_do_registro', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # op.drop_table('consumo_agua', schema='main')
    # with op.batch_alter_table('consumo_agua_version', schema='main') as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_main_consumo_agua_version_transaction_id'))
    #     batch_op.drop_index(batch_op.f('ix_main_consumo_agua_version_operation_type'))
    #     batch_op.drop_index(batch_op.f('ix_main_consumo_agua_version_end_transaction_id'))

    # op.drop_table('consumo_agua_version', schema='main')
    # ### end Alembic commands ###
    pass
