"""empty message

Revision ID: fb690082cf58
Revises: 5dde578b7d2b
Create Date: 2023-10-19 20:03:32.711489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb690082cf58'
down_revision = '5dde578b7d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumo_agua', schema='main') as batch_op:
        batch_op.add_column(sa.Column('consumo', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('data', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('dataFimPeriodo', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('dataInicioPeriodo', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('valor', sa.Float(), nullable=True))
        batch_op.drop_constraint('consumo_agua_consumo_m3_key', type_='unique')
        batch_op.create_unique_constraint(None, ['consumo'])
        batch_op.drop_column('consumo_m3')
        batch_op.drop_column('inicio_medicao')
        batch_op.drop_column('fim_medicao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumo_agua', schema='main') as batch_op:
        batch_op.add_column(sa.Column('fim_medicao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('inicio_medicao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('consumo_m3', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('consumo_agua_consumo_m3_key', ['consumo_m3'])
        batch_op.drop_column('valor')
        batch_op.drop_column('dataInicioPeriodo')
        batch_op.drop_column('dataFimPeriodo')
        batch_op.drop_column('data')
        batch_op.drop_column('consumo')

    # ### end Alembic commands ###
