Recuperar uma lista com os locais
---
tags:
  - Configurações
parameters:
  - name: tipo
    description: Id do tipo de local que deseja recuperar
    in: path
    required: true
    type: integer
    example: 1
responses:
  200:
    description: Retorno realizado com sucesso

  400:
    description: Falha ao realizar a requisição